# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "prj10"
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.provision "file", source: "empty_file", destination: "empty_file"
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
	sudo apt-get install -y python3 python3-pip libpq-dev 
	sudo pip3 install psycopg2
	sudo pip3 install Django
  SHELL
end